### ISSUE TITLE
Many issues and questions on this

### ISSUE THREAD

**Issue by TheGamingCats** [MC-Prison/Prison#37]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?
Spigot, Ranks, Core, Shops
Example: Core, Mines, Ranks, Shops, Cells, Gangs, Spigot, Sponge, etc.

### Describe the issue you are experiencing.
Include details such as what you did, what happened, and what you think should have happened.
1. Is there a sell all sign?
2. I was not able to delete my rank and had to delete my entire Prison folder due to an error.
3. How do you set a default rank?
4. What are the Prison permissions..?
5. Rank tag not working? It doesn't show up in chat
If the tag is not supposed to show, how do I get it to?
6. Is this a rank on my permissions plugin? If so, why don't I see it on the list of ranks on my PEX?
7. What are rank commands?
8. Using Essentials, how do you increase the money limit of 10 trillion? I need it for my ranks.
9. Will there be plots?

### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.
Prison - 1.0.0 SNAPSHOT
Spigot - 1.12

### Anything else we need to know?
No.
If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by faizaand** [comment]
Thanks for finding these potential issues in the beta version of Prison 3.

1. Prison, as of now, does not have a selling system. You can use plugins such as ChestShop or Essentials Signs for selling signs. PrisonShops is coming soon.

2. What was the error message?

3. The first rank you create is the default rank. A setting for this will be added shortly.

4. The permissions can be found [here](https://raw.githubusercontent.com/MC-Prison/PrisonMines/master/src/main/resources/plugin.yml) and also for ranks, [here](https://raw.githubusercontent.com/MC-Prison/PrisonRanks/master/src/main/resources/plugin.yml).

5. You can show the rank tag by adding `{PRISON_RANK}` to your chat format plugin.

6. Ranks are no longer attached to the permissions plugin. In order to add your players to a permissions group when they rank up, you must add a **rank command**. To do this, type `/rank command add A pex group A user add {player}` (adjusted to your rank and group, of course).

7. Rank commands are run whenever a user ranks up to a rank. See above for an example. You can add as many rank commands as you want.

8. You can view the Essentials config.yml file to increase the money limit.

9. No, not built into Prison. You can use the plugin PlotSquared for plots.

If you have any more questions, please ask here and I will respond as fast as possible. Thank you for reporting your issues.

**Comment by TheGamingCats** [comment]
I see. Thanks so much for answering to my queries! I just want to ask, will the commands have OP permission or will the command follow the permission that the player has?

**Comment by TheGamingCats** [comment]
Also, my PrisonMines module suddenly stopped working for some reason after I deleted the Prison folder to reset the plugin.

**Comment by faizaand** [comment]
@TheGamingCats Can you give me all of the errors you've been experiencing from the console? That will help me figure out what's going on.
