### ISSUE TITLE
Documentation for Initial Release

### ISSUE THREAD

**Issue by faizaand** [MC-Prison/Prison#44]
Aside from updating, the last obstacle in the way of releasing Prison 3 is documentation.

- [x] Installation and Setup
  - [x] Include chat format for ranks
- [x] Creating mines
- [x] Creating ranks
- [x] Using multiple rank ladders

**Comment by Lmmb74** [comment]
I would gladly help you making documentation for your project.

**Comment by faizaand** [comment]
Great! I'm currently working on the checklist.

**Comment by Lmmb74** [comment]
As I am Argentinian, I would also be able to make a Spanish translation of both the documentation and the default plugin messages.

**Comment by Lmmb74** [comment]
I found out some things that may or not cause incompatibility issues:

Prison (Spigot):
- SaneEconomy 0.11,0 is used as dependency - Updated version: 0.13.1
- LuckPerms 2.17.38 is used as depencency - Updated version: 4.0.69 (Major API change)

Ranks & Mines Modules:
- PrisonCore 0.15.0-SNAPSHOT is used as dependency - Updated REPO version: 1.0.0-SNAPSHOT (2017-07-13)

Cells Module:
- PrisonCore is included in libs folder, not used from REPO as Ranks & Mines

I will also inclued the Modules last commit dates due to the fact that the API may have changed a lot since then:
- Ranks; 12th July
- Mines; 12th July
- Cells: 7th January

Also, Gangs Module has not been developed.

**Comment by DylanFPS** [comment]
@Lmmb74 The cells module should be completely discarded as I neither finished it or get it in a state that can be considered acceptable. Frankly, the devs would have a hard time working with the messy code in there.

**Comment by cbwolfe32** [comment]
@Lmmb74 gangs module was something I was planning on working on but I decided other things were important. In fact, this entire thing has become the absolute bottom of I think everyone's todo list until now, it's slightly higher. Still low on my list, but for @faizaand it's fairly high.

**Comment by faizaand** [comment]
I updated Prison-Spigot's dependencies here c22d397

**Comment by Lmmb74** [comment]
@faizaand Do you have any news about Gangs or Cells modules?

**Comment by cbwolfe32** [comment]
Gangs is an abandoned project as of now.

**Comment by Lmmb74** [comment]
u.u

**Comment by faizaand** [comment]
Documentation is complete.  https://github.com/MC-Prison/Prison/wiki/

**Comment by DylanFPS** [comment]
@Lmmb74 I will restart work on Cells after rewriting Mines to be more like Ranks
